import { topicDetails } from './topicDetails';

const p = (id, title, goal, topics, projects) => ({
  id,
  title,
  goal,
  topics: topics
    .filter(topic => !/^1\.1\.[1-4]\s/.test(topic))
    .map(topic => {
      if (!topicDetails[topic]) throw new Error(`Missing roadmap details for: ${topic}`);
      return { title: topic, subtopics: topicDetails[topic] };
    }),
  projects,
});

export const roadmap = [
  p(1, 'Programming Foundation', 'Write clean, production-quality Python for AI workflows.', ['1.1 Python Fundamentals', '1.1.1 Integers, floats, strings, booleans, None', '1.1.2 Type conversion: int(), float(), str(), bool()', '1.1.3 type() and isinstance()', '1.1.4 Mutable vs immutable types - critical for AI pipelines', '1.2 Functions', '1.3 Object-Oriented Programming', '1.4 Pythonic Code & Idioms', '1.5 File I/O & Data Handling', '1.6 Error Handling & Debugging', '1.7 Performance & Memory', '1.8 NumPy (Non-Negotiable for AI)', '1.9 Pandas (Essential for Data Work)', '1.10 Code Quality & Project Structure', '1.11 Python for AI Workflows', '1.12 Async Python (Critical for AI APIs)'], ['Python AI Toolkit CLI', 'Async Multi-API Caller', 'Production-Grade Data Pipeline']),
  p(2, 'Mathematics & Statistics for AI', 'Understand the math behind what models do without getting stuck in derivations.', ['2.1 Linear Algebra', '2.2 Calculus', '2.3 Probability & Statistics', '2.4 Optimization', '2.5 Information Theory'], ['Cosine Similarity Search', 'Gradient Descent Visualizer', 'Build Your Own Neural Network from Scratch']),
  p(3, 'Machine Learning Fundamentals', 'Understand classic ML algorithms, feature engineering and evaluation.', ['3.1 Core ML Concepts', '3.2 Linear & Logistic Regression', '3.3 Decision Trees & Ensembles', '3.4 Unsupervised Learning', '3.5 Hyperparameter Tuning', '3.6 ML with Scikit-Learn'], ['Spam Classifier', 'Customer Churn Prediction System', 'AutoML Mini-Framework']),
  p(4, 'Deep Learning', 'Understand neural networks deeply enough to work with transformers.', ['4.1 Neural Network Fundamentals', '4.2 Training Techniques', '4.3 Convolutional Neural Networks (CNN)', '4.4 Recurrent Neural Networks (RNN)', '4.5 Attention Mechanism (Pre-Transformer)', '4.6 PyTorch (Master This)', '4.7 Transfer Learning'], ['Image Classifier with Transfer Learning', 'Sentiment Analysis with LSTM vs BERT', 'Build a Mini GPT from Scratch']),
  p(5, 'Natural Language Processing & Transformers', 'Build deep NLP intuition and master the transformer architecture.', ['5.1 Text Preprocessing', '5.2 Classical Text Representation', '5.3 Word Embeddings', '5.4 Subword Tokenization (Modern)', '5.5 Transformer Architecture (Master This)', '5.6 Language Modeling', '5.7 Key Pretrained Models', '5.8 NLP Evaluation Metrics', '5.9 Key Python Libraries'], ['Named Entity Recognition (NER) Pipeline', 'Semantic Search Engine', 'Fine-tune BERT for Multi-Label Classification']),
  p(6, 'Large Language Models & AI Engineering', 'Master LLM fundamentals, APIs and production patterns.', ['6.1 LLM Fundamentals', '6.2 Prompt Engineering (Production-Grade)', '6.3 Working with AI APIs', '6.4 API Integration Patterns', '6.5 Secure API Integration'], ['Multi-Provider AI Chatbot', 'AI-Powered Resume Ranker', 'Production AI Middleware Service']),
  p(7, 'Multi-LLM Orchestration (Your Specialty)', 'Design production-grade systems with routing, fallbacks and model selection.', ['7.1 Why Multi-LLM Architecture', '7.2 Routing Strategies', '7.3 Fallback Architecture', '7.4 Model Context Protocol (MCP)', '7.5 LLM Orchestration Frameworks', '7.6 Building PrinceSinghAI / PrinceSinghDev Style Systems'], ['LLM Router Dashboard', 'Intelligent Multi-LLM Router', 'Production Multi-LLM Orchestration Platform']),
  p(8, 'RAG & Vector Databases', 'Give LLMs access to private and changing knowledge.', ['8.1 Why RAG Exists', '8.2 Embeddings Deep Dive', '8.3 Chunking Strategies', '8.4 Vector Databases', '8.5 RAG Pipeline Implementation', '8.6 Production RAG Considerations'], ['Chat with Your PDF', 'Multi-Document Knowledge Base', 'Enterprise RAG System']),
  p(9, 'AI Agents & Agentic Systems', 'Build systems that reason, plan and take actions with tools.', ['9.1 What Are AI Agents', '9.2 Agent Components', '9.3 Function Calling / Tool Use', '9.4 Multi-Agent Systems', '9.5 Agentic AI (AskAI Framework)'], ['ReAct Agent with Web Search', 'Code Review Agent', 'Autonomous Research Agent (AskAI)']),
  p(10, 'Fine-Tuning & Model Customization', 'Customize models for specific domains and use cases.', ['10.1 When to Fine-Tune', '10.2 Full Fine-Tuning', '10.3 Parameter-Efficient Fine-Tuning (PEFT)', '10.4 Fine-Tuning Tools', '10.5 Dataset Preparation', '10.6 Evaluation After Fine-Tuning'], ['Fine-tune GPT-3.5 on Custom Q&A', 'LoRA Fine-tune LLaMA on Code', 'Full RLHF Pipeline (CodeLLM Context)']),
  p(11, 'Generative AI (Beyond Text)', 'Understand image, multimodal, audio and video generation.', ['11.1 Variational Autoencoders (VAEs)', '11.2 Generative Adversarial Networks (GANs)', '11.3 Diffusion Models', '11.4 Text-to-Image APIs', '11.5 Multimodal AI', '11.6 Audio AI', '11.7 Video AI'], ['Image + Text Multi-Modal QA', 'AI Image Generation Pipeline', 'Voice AI Assistant (Full Pipeline)']),
  p(12, 'MLOps, LLMOps & Production Systems', 'Ship AI reliably, cheaply and scalably.', ['12.1 Data Management & Versioning', '12.2 Experiment Tracking', '12.3 Model Development & Training Infrastructure', '12.4 Model Evaluation & Testing', '12.5 Model Deployment & Serving', '12.6 Containerization & Orchestration', '12.7 Cloud Deployment', '12.8 Monitoring & Logging', '12.9 CI/CD for AI', '12.10 LLM Security & Safety'], ['Dockerize an AI API', 'LLMOps Monitoring Dashboard', 'Production AI Platform on Kubernetes']),
  p(13, 'AI System Design', 'Design scalable AI systems for real products and interviews.', ['13.1 AI System Design Framework', '13.2 Classic AI System Designs', '13.3 Inference Placement Strategy', '13.4 Caching Strategies', '13.5 Async AI Architecture', '13.6 Cost-Aware Architecture'], ['Design Doc for AI Feature', 'Cost Calculator Tool', 'Full AI System Design Implementation']),
  p(14, 'SQL & Databases for AI Engineers', 'Query confidently and design databases that support AI systems.', ['14.1 Core SQL', '14.2 Advanced SQL', '14.3 AI-Specific SQL Patterns', '14.4 Database Design for AI Applications', '14.5 NoSQL for AI'], ['AI Usage Analytics Dashboard', 'pgvector Semantic Search', 'Complete Database Architecture for AI Platform']),
  p(15, 'Quantization, Optimization & Efficiency', 'Run models efficiently at scale.', ['15.1 Model Quantization', '15.2 Inference Optimization', '15.3 Small Language Models (SLMs)', '15.4 Knowledge Distillation', '15.5 Model Serving Efficiency'], ['Local LLM Setup', 'Model Quantization Comparison', 'High-Throughput Inference Server (CodeLLM)']),
  p(16, 'Reinforcement Learning for AI Engineers', 'Understand RL well enough to work with RLHF, PPO and agentic training.', ['16.1 RL Fundamentals', '16.2 Value-Based Methods', '16.3 Policy-Based Methods', '16.4 RL for LLMs (RLHF & Beyond)', '16.5 Multi-Agent RL'], ['Train a CartPole Agent', 'Reward Model Training', 'DPO Fine-tuning Pipeline']),
  p(17, 'AI Ethics, Safety & Governance', 'Build AI responsibly. This is increasingly a job requirement.', ['17.1 AI Safety Fundamentals', '17.2 Prompt Injection & Security', '17.3 Bias & Fairness', '17.4 Privacy & Data Governance', '17.5 AI Transparency & Explainability', '17.6 Responsible AI in Production'], ['AI Safety Checklist', 'Prompt Injection / Red-Team Lab', 'Responsible AI Governance Plan']),
  p(18, 'Capstone: Build Your Production AI System', 'Build a complete production AI system that demonstrates the full stack.', ['API Gateway', 'Multi-LLM Router', 'RAG Engine', 'Agent Orchestrator', 'MCP Integration', 'Observability Stack', 'Admin Dashboard', 'CI/CD Pipeline', 'Multi-tenant user management', 'Per-user API key management', 'Streaming responses', 'Conversation memory', 'Prompt version management', 'A/B testing for prompts and models', 'Cost tracking dashboard', 'Usage limits and billing'], ['Capstone architecture', 'Production MVP', 'Portfolio-ready final demo']),
];
