export const topicDetails = {
  '1.1 Python Fundamentals': [
    'Integers, floats, strings, booleans, and None',
    'Convert values with int(), float(), str(), and bool()',
    'Inspect values with type() and isinstance()',
    'Mutable and immutable values in data pipelines',
    'String slicing, common methods, and formatted strings',
    'Lists, tuples, dictionaries, sets, and nested collections',
    'Conditions, loops, range(), enumerate(), and zip()',
  ],
  '1.2 Functions': [
    'Define functions and document them with docstrings',
    'Use positional, keyword, and default arguments',
    'Handle flexible arguments with *args and **kwargs',
    'Return values, unpack tuples, and write lambdas',
    'Understand recursion and its practical limits',
  ],
  '1.3 Object-Oriented Programming': [
    'Create classes, instances, constructors, and instance methods',
    'Distinguish class variables from instance variables',
    'Use inheritance, super(), and method overriding',
    'Implement useful dunder methods such as __repr__ and __getitem__',
    'Use properties, class/static methods, and abstract classes',
  ],
  '1.4 Pythonic Code & Idioms': [
    'Build list, dictionary, and set comprehensions',
    'Use generators, yield, and generator expressions for streaming',
    'Apply map(), filter(), reduce(), any(), and all()',
    'Unpack iterables and sort with a key function',
    'Use Counter, defaultdict, and deque from collections',
  ],
  '1.5 File I/O & Data Handling': [
    'Read and write files with open() and context managers',
    'Parse CSV and JSON data; understand pickle for Python objects',
    'Manage paths and directories with pathlib and os',
    'Find matching files with glob patterns',
  ],
  '1.6 Error Handling & Debugging': [
    'Use try, except, and finally with specific exception types',
    'Raise errors and define custom exception classes',
    'Use logging levels to diagnose application behavior',
    'Debug with breakpoints and interpret tracebacks',
  ],
  '1.7 Performance & Memory': [
    'Stream large workloads with generators and itertools',
    'Benchmark code with timeit and cProfile',
    'Choose between shallow and deep copies',
    'Prefer vectorized operations to Python loops for array workloads',
  ],
  '1.8 NumPy (Non-Negotiable for AI)': [
    'Create arrays and inspect shape, dimensions, and dtype',
    'Reshape, flatten, and combine arrays',
    'Use boolean indexing, where(), and broadcasting',
    'Apply dot products, matrix operations, and linear algebra tools',
    'Aggregate over axes and generate reproducible random values',
  ],
  '1.9 Pandas (Essential for Data Work)': [
    'Create and inspect DataFrames and Series',
    'Select rows and columns with loc, iloc, and boolean filters',
    'Detect, remove, or fill missing values',
    'Summarize data with groupby, agg, pivot_table, and value_counts',
    'Combine and reshape tables with merge, concat, and melt',
    'Parse date columns with to_datetime()',
  ],
  '1.10 Code Quality & Project Structure': [
    'Create isolated environments and manage dependency files',
    'Organize reusable modules and Python packages',
    'Add type hints and use dataclasses for structured data',
    'Write unit tests with pytest',
    'Lint and format code with Ruff/Flake8 and Black',
  ],
  '1.11 Python for AI Workflows': [
    'Use notebooks and Colab for exploration and GPU access',
    'Add progress reporting and command-line arguments to scripts',
    'Manage experiment settings with YAML or Hydra',
    'Keep API keys in environment configuration; never commit secrets',
    'Seed random libraries and save/load models for reproducibility',
  ],
  '1.12 Async Python (Critical for AI APIs)': [
    'Write coroutines with async/await and understand the event loop',
    'Make asynchronous HTTP requests with aiohttp or httpx',
    'Run independent provider calls concurrently with asyncio.gather()',
    'Use asynchronous iteration for streamed model responses',
  ],
  '2.1 Linear Algebra': [
    'Work with vectors, norms, normalization, and cosine similarity',
    'Distinguish element-wise operations from matrix multiplication',
    'Apply linear transformations and solve Ax = b or least-squares problems',
    'Understand eigenvectors, eigenvalues, rank, and matrix decompositions',
    'Connect SVD and dimensionality reduction to embedding workflows',
  ],
  '2.2 Calculus': [
    'Interpret derivatives and apply common differentiation rules',
    'Use partial derivatives, gradients, Jacobians, and Hessians',
    'Trace the chain rule through computational graphs and backpropagation',
    'Understand derivatives of sigmoid, ReLU, softmax, and common losses',
  ],
  '2.3 Probability & Statistics': [
    'Calculate joint, marginal, conditional, and independent probabilities',
    'Apply Bayes theorem and interpret prior, likelihood, and posterior',
    'Describe random variables, distributions, expectation, and variance',
    'Recognize common distributions and the Central Limit Theorem',
    'Connect MLE, MAP, entropy, and KL divergence to model training',
  ],
  '2.4 Optimization': [
    'Compare objective functions, convexity, and local/global optima',
    'Implement gradient descent and compare batch, stochastic, and minibatch updates',
    'Understand momentum, RMSProp, Adam, and learning-rate schedules',
    'Diagnose vanishing/exploding gradients and use clipping',
    'Apply weight decay, sparsity, dropout, and early stopping',
  ],
  '2.5 Information Theory': [
    'Calculate entropy and interpret information content',
    'Relate cross-entropy to classification loss',
    'Use KL divergence in VAEs, distillation, and RL objectives',
    'Understand mutual information and bits versus nats',
  ],
  '3.1 Core ML Concepts': [
    'Distinguish supervised, unsupervised, and reinforcement learning',
    'Separate training, validation, and test data',
    'Diagnose overfitting, underfitting, and the bias-variance trade-off',
    'Use cross-validation and select suitable evaluation metrics',
  ],
  '3.2 Linear & Logistic Regression': [
    'Fit linear regression with closed-form and gradient-based methods',
    'Use logistic regression and sigmoid scores for classification',
    'Compare MSE and binary cross-entropy objectives',
    'Apply Ridge, Lasso, and one-vs-rest classification',
  ],
  '3.3 Decision Trees & Ensembles': [
    'Split decision trees using Gini impurity or entropy',
    'Explain bagging and how random forests combine trees',
    'Compare gradient-boosting libraries such as XGBoost and LightGBM',
    'Interpret feature importance and its limitations',
  ],
  '3.4 Unsupervised Learning': [
    'Cluster data with K-Means and DBSCAN',
    'Use PCA for dimensionality reduction',
    'Visualize high-dimensional embeddings with t-SNE or UMAP',
  ],
  '3.5 Hyperparameter Tuning': [
    'Compare grid search, random search, and Bayesian optimization',
    'Tune learning rate, batch size, epochs, and model depth',
    'Use early stopping to limit overfitting and wasted compute',
  ],
  '3.6 ML with Scikit-Learn': [
    'Build preprocessing and estimator pipelines',
    'Scale numerical features and encode categorical values',
    'Select models with GridSearchCV and cross_val_score',
    'Use the fit/transform/predict API and persist models with joblib',
  ],
  '4.1 Neural Network Fundamentals': [
    'Build intuition for neurons, perceptrons, and multilayer networks',
    'Compare sigmoid, tanh, ReLU, GELU, and SwiGLU activations',
    'Trace forward propagation and backpropagation',
    'Choose weight initialization and recognize vanishing/exploding gradients',
  ],
  '4.2 Training Techniques': [
    'Compare batch normalization and transformer-style layer normalization',
    'Use dropout as a regularization method',
    'Explain residual connections and their role in deep networks',
    'Apply gradient clipping during unstable training',
  ],
  '4.3 Convolutional Neural Networks (CNN)': [
    'Understand convolution filters and pooling operations',
    'Compare LeNet, AlexNet, VGG, and ResNet architectures',
    'Adapt pretrained CNNs through transfer learning',
    'Apply CNNs to classification and object-detection tasks',
  ],
  '4.4 Recurrent Neural Networks (RNN)': [
    'Model sequential inputs with recurrent hidden states',
    'Understand vanishing gradients and LSTM/GRU gates',
    'Compare bidirectional and sequence-to-sequence architectures',
    'Decode generated sequences with beam search',
  ],
  '4.5 Attention Mechanism (Pre-Transformer)': [
    'Interpret attention as soft alignment over input positions',
    'Compare additive and multiplicative attention',
    'Trace Bahdanau attention in sequence-to-sequence models',
    'Explain how attention eases the encoder-decoder bottleneck',
  ],
  '4.6 PyTorch (Master This)': [
    'Create tensors and move data between CPU and GPU',
    'Build modules, custom datasets, and data loaders',
    'Write the training loop: forward pass, loss, backward pass, optimizer step',
    'Control gradients and switch between train and evaluation modes',
    'Save/load checkpoints and configure losses and learning-rate schedulers',
  ],
  '4.7 Transfer Learning': [
    'Explain pretraining and reuse pretrained representations',
    'Choose between feature extraction and fine-tuning',
    'Freeze selected layers to control training cost',
    'Load pretrained vision and language models from Hugging Face',
  ],
  '5.1 Text Preprocessing': [
    'Tokenize text and normalize case, punctuation, and whitespace',
    'Choose whether to remove stop words; compare stemming and lemmatization',
    'Segment sentences and handle URLs, emails, and hashtags',
    'Preserve Unicode text and use consistent UTF-8 encoding',
  ],
  '5.2 Classical Text Representation': [
    'Represent text with bag-of-words and TF-IDF',
    'Use n-grams to capture local word context',
    'Understand one-hot encoding and sparse feature matrices',
    'Compare sparse classical vectors with dense embeddings',
  ],
  '5.3 Word Embeddings': [
    'Explain dense vectors and semantic similarity',
    'Compare Word2Vec CBOW/Skip-gram, GloVe, and FastText',
    'Measure embedding similarity and solve analogy-style examples',
    'Distinguish static embeddings from contextual representations',
  ],
  '5.4 Subword Tokenization (Modern)': [
    'Compare BPE, WordPiece, and SentencePiece tokenization',
    'Recognize special tokens and their roles in model inputs',
    'Map text to token IDs and inspect tokenizer output',
    'Evaluate vocabulary-size trade-offs and token fragmentation',
  ],
  '5.5 Transformer Architecture (Master This)': [
    'Compute self-attention with query, key, and value projections',
    'Explain scaled dot-product attention and multi-head attention',
    'Understand positional encoding, feed-forward layers, and residual normalization',
    'Compare encoder-only, decoder-only, and encoder-decoder designs',
    'Explain causal masks and why transformers parallelize sequence processing',
  ],
  '5.6 Language Modeling': [
    'Model next-token probabilities and autoregressive generation',
    'Compare causal language modeling with masked language modeling',
    'Use perplexity to assess language-model predictions',
    'Control generation with temperature, top-k, top-p, and decoding strategy',
  ],
  '5.7 Key Pretrained Models': [
    'Compare encoder-only BERT with decoder-only GPT and LLaMA families',
    'Recognize encoder-decoder models such as T5 and multimodal Gemini',
    'Match model families to classification, generation, and sequence tasks',
    'Compare hosted models with open-weight options such as Mistral and Qwen',
  ],
  '5.8 NLP Evaluation Metrics': [
    'Use precision, recall, F1, and accuracy for classification',
    'Apply BLEU to translation and ROUGE to summarization',
    'Evaluate language models with perplexity and QA with exact match',
    'Compare semantic metrics such as BERTScore with human review',
  ],
  '5.9 Key Python Libraries': [
    'Use NLTK and spaCy for text processing and named entities',
    'Load pretrained models and datasets with Transformers and Datasets',
    'Generate sentence embeddings and tokenize with dedicated libraries',
    'Evaluate models with the Hugging Face Evaluate toolkit',
  ],
  '6.1 LLM Fundamentals': [
    'Understand context windows, tokenization, and inference-time KV caches',
    'Compare positional methods such as RoPE and ALiBi',
    'Recognize efficient attention methods, GQA, and sliding windows',
    'Trace pretraining, instruction tuning, RLHF, DPO, and Constitutional AI',
    'Relate scaling laws to model size, data, and compute',
  ],
  '6.2 Prompt Engineering (Production-Grade)': [
    'Structure system instructions, user requests, and conversation examples',
    'Apply zero/few-shot, CoT, ReAct, self-consistency, and structured output',
    'Set clear constraints, examples, and boundaries for reliable outputs',
    'Version prompts, A/B test changes, and defend against prompt injection',
  ],
  '6.3 Working with AI APIs': [
    'Use chat, tool calling, structured output, streaming, and embeddings APIs',
    'Work with provider-specific vision, files, batch, and long-context features',
    'Compare OpenAI, Anthropic, Gemini, and Mistral API conventions',
    'Connect open-weight models and hosted providers through common clients',
    'Track token counts, quotas, and provider rate limits',
  ],
  '6.4 API Integration Patterns': [
    'Count tokens and manage context-window limits and conversation history',
    'Stream partial responses to clients with server-sent events',
    'Use retry backoff, jitter, queues, and circuit breakers',
    'Control cost with usage logging, model routing, and caching',
    'Fall back to another provider, cached output, or a safe default on failure',
  ],
  '6.5 Secure API Integration': [
    'Keep provider credentials on the server and out of browser bundles',
    'Store secrets in environment files locally and secret managers in production',
    'Proxy provider requests through a backend with per-user limits',
    'Rotate keys and monitor access and usage',
  ],
  '7.1 Why Multi-LLM Architecture': [
    'Route work to models suited to each task rather than choosing one universal model',
    'Balance quality against spend and response latency',
    'Add provider failover to improve availability',
    'Honor compliance, context-window, and customer-provider constraints',
  ],
  '7.2 Routing Strategies': [
    'Classify tasks and route code, long-context, vision, and embedding requests',
    'Apply user-tier and token-budget rules for cost-aware routing',
    'Track quality, latency, and user feedback per model and task',
    'Use A/B tests and service-level targets to tune routing decisions',
  ],
  '7.3 Fallback Architecture': [
    'Order primary, secondary, and lower-cost backup providers',
    'Use cached or static responses when providers are unavailable',
    'Open circuits after repeated failures and test recovery in half-open state',
    'Record fallback paths and monitor provider health',
  ],
  '7.4 Model Context Protocol (MCP)': [
    'Compare MCP with direct function calling and provider tool-use APIs',
    'Understand MCP server tools, resources, and prompts and client connections',
    'Build MCP servers in Python or TypeScript',
    'Connect tools to databases, APIs, and filesystems with least privilege',
    'Plan MCP security for agent and multi-agent workflows',
  ],
  '7.5 LLM Orchestration Frameworks': [
    'Compose chains, tools, memory, and retrieval with LangChain and LCEL',
    'Model stateful cyclic workflows, checkpointing, and human review in LangGraph',
    'Use LlamaIndex connectors, indexes, and query engines for data workflows',
    'Compare CrewAI role/task flows and AutoGen multi-agent conversations',
    'Trace and inspect executions with framework observability tools',
  ],
  '7.6 Building PrinceSinghAI / PrinceSinghDev Style Systems': [
    'Route requests through an authenticated, rate-limited API gateway',
    'Create a unified provider layer, classifier, and response aggregator',
    'Track per-user tokens and cost; validate responses and cache results',
    'Add provider fallbacks and semantic caching',
    'Instrument traces, metrics, and logs across the system',
  ],
  '8.1 Why RAG Exists': [
    'Use retrieval for private knowledge and information beyond model training cutoffs',
    'Ground answers in retrieved material to reduce unsupported responses',
    'Combine semantic retrieval with prompt-based generation',
    'Choose between RAG and fine-tuning based on the need and data',
  ],
  '8.2 Embeddings Deep Dive': [
    'Represent text as dense vectors with embedding models',
    'Compare hosted and open-source embedding model choices',
    'Evaluate dimension, quality, storage, and batch throughput trade-offs',
    'Search vectors with cosine similarity, dot product, or Euclidean distance',
  ],
  '8.3 Chunking Strategies': [
    'Compare fixed-size, sentence-based, recursive, and semantic chunking',
    'Split structured documents by sections and headers',
    'Tune chunk size and overlap for context and retrieval quality',
    'Preserve source, page, and section metadata for citations',
  ],
  '8.4 Vector Databases': [
    'Compare local, embedded, managed, and PostgreSQL vector stores',
    'Store embeddings with metadata and build vector indexes',
    'Use nearest-neighbor and metadata-filtered retrieval',
    'Combine keyword BM25 with vector search for hybrid retrieval',
    'Isolate namespaces or collections for multi-tenant applications',
  ],
  '8.5 RAG Pipeline Implementation': [
    'Ingest, chunk, embed, and index source documents',
    'Embed user questions and retrieve the most relevant passages',
    'Improve retrieval with HyDE, query expansion, reranking, and compression',
    'Evaluate faithfulness, relevance, context precision, and recall',
  ],
  '8.6 Production RAG Considerations': [
    'Update indexes incrementally and track document versions',
    'Isolate tenant data and cache embeddings or query results',
    'Monitor retrieval quality, latency, and cache behavior',
    'Respond safely when retrieved evidence is insufficient',
  ],
  '9.1 What Are AI Agents': [
    'Model agents as LLMs working with tools, memory, and planning',
    'Compare dynamic agents with deterministic chains',
    'Recognize ReAct, plan-and-execute, and multi-agent patterns',
    'Choose agents only when their autonomy justifies cost and risk',
  ],
  '9.2 Agent Components': [
    'Provide tools for search, code, databases, files, and APIs',
    'Compare in-context, external, entity, summary, and episodic memory',
    'Use ReAct, plan-and-execute, or tree-search planning patterns',
    'Set tool permissions and boundaries for each agent',
  ],
  '9.3 Function Calling / Tool Use': [
    'Define tools with JSON schemas and submit them with model requests',
    'Parse tool requests, validate inputs, execute, and return results',
    'Support multi-step and parallel tool calls',
    'Add timeouts, error handling, authorization, and sandboxing',
  ],
  '9.4 Multi-Agent Systems': [
    'Compare supervisor-worker, peer, pipeline, and critic-generator designs',
    'Coordinate shared state, conditional routing, and parallel agent work',
    'Add human checkpoints and clear agent communication protocols',
    'Apply patterns to code review, research, software delivery, and support',
  ],
  '9.5 Agentic AI (AskAI Framework)': [
    'Design autonomy, goal direction, persistence, and feedback-driven adaptation',
    'Decompose tasks and track progress across steps',
    'Recover from errors and escalate to a person when needed',
    'Add action confirmation, spending limits, sandboxing, and audit trails',
  ],
  '10.1 When to Fine-Tune': [
    'Consider fine-tuning for consistent formats or repeated domain tasks',
    'Compare fine-tuning with prompt engineering and retrieval costs',
    'Check data quality and example volume before committing to training',
    'Use retrieval rather than fine-tuning when facts must stay current',
  ],
  '10.2 Full Fine-Tuning': [
    'Prepare prompt/completion examples and separate validation data',
    'Run provider fine-tuning APIs or a Hugging Face Trainer workflow',
    'Tune learning rate, epochs, and batch size while monitoring overfit',
    'Prioritize clean representative examples over raw dataset size',
  ],
  '10.3 Parameter-Efficient Fine-Tuning (PEFT)': [
    'Add LoRA low-rank matrices and tune rank, scaling, and target layers',
    'Merge LoRA weights when preparing deployment artifacts',
    'Apply QLoRA to quantized base models using NF4 representations',
    'Compare prefix tuning, prompt tuning, and IA3 with LoRA',
  ],
  '10.4 Fine-Tuning Tools': [
    'Use Hugging Face PEFT for adapter-based training',
    'Apply TRL workflows for supervised tuning, preference training, and DPO',
    'Compare Unsloth, Axolotl, and LLaMA-Factory training workflows',
    'Track runs and artifacts with Weights & Biases or MLflow',
  ],
  '10.5 Dataset Preparation': [
    'Format instruction, chat, and chosen/rejected preference examples',
    'Clean, deduplicate, and quality-filter training records',
    'Create validation data and apply appropriate augmentation',
    'Balance data sources with deliberate data-mixing strategies',
  ],
  '10.6 Evaluation After Fine-Tuning': [
    'Select task metrics such as F1, accuracy, BLEU, or ROUGE',
    'Benchmark with suites relevant to the task and model',
    'Combine human review with model-as-judge scoring',
    'Run regression tests to detect capability loss elsewhere',
  ],
  '11.1 Variational Autoencoders (VAEs)': [
    'Trace encoder, latent representation, and decoder',
    'Balance reconstruction and KL-divergence losses',
    'Understand the reparameterization trick',
    'Apply VAEs to generation and anomaly detection',
  ],
  '11.2 Generative Adversarial Networks (GANs)': [
    'Train generator and discriminator in an adversarial objective',
    'Recognize mode collapse and training instability',
    'Compare conditional GANs, DCGAN, and StyleGAN families',
    'Apply GANs to image synthesis and style transfer',
  ],
  '11.3 Diffusion Models': [
    'Describe forward noising and learned reverse denoising',
    'Understand DDPM, score matching, and faster DDIM sampling',
    'Control generations with classifier-free guidance',
    'Explore Stable Diffusion components and ControlNet conditioning',
  ],
  '11.4 Text-to-Image APIs': [
    'Compare hosted image-generation services and open diffusion models',
    'Write prompts that specify subject, style, and composition',
    'Use negative prompts where supported',
    'Wrap image generation in an application API and review safety controls',
  ],
  '11.5 Multimodal AI': [
    'Process text and images with vision-language models',
    'Compare hosted multimodal models with open VLMs such as LLaVA',
    'Relate CLIP embeddings to aligned text-image representations',
    'Build captioning, visual question answering, and document understanding',
  ],
  '11.6 Audio AI': [
    'Transcribe speech with Whisper-style speech recognition',
    'Generate speech with hosted or open text-to-speech systems',
    'Explore music generation and voice cloning capabilities',
    'Design low-latency streaming audio workflows',
  ],
  '11.7 Video AI': [
    'Explore text-to-video generation systems',
    'Analyze video with multimodal models',
    'Extract and sample frames for frame-by-frame processing',
  ],
  '12.1 Data Management & Versioning': [
    'Version datasets and models with DVC-style workflows',
    'Validate data contracts with Great Expectations or Pandera',
    'Track lineage from source data to trained model',
    'Use feature stores and orchestrated data pipelines where appropriate',
  ],
  '12.2 Experiment Tracking': [
    'Track parameters, metrics, artifacts, and source revision per run',
    'Compare runs and publish experiment reports',
    'Choose a hosted or open-source tracking platform',
  ],
  '12.3 Model Development & Training Infrastructure': [
    'Choose managed training services or GPU compute',
    'Scale training with DDP, DeepSpeed, or FSDP',
    'Use FP16/BF16 mixed precision and model checkpoints',
    'Monitor training progress and alert on failures',
  ],
  '12.4 Model Evaluation & Testing': [
    'Run task benchmarks, guided human reviews, and red-team tests',
    'Use model-based judges with validation safeguards',
    'Compare production candidates with A/B and shadow deployments',
    'Roll out gradually with canaries and collect user feedback',
  ],
  '12.5 Model Deployment & Serving': [
    'Expose models through REST or gRPC services and serving frameworks',
    'Optimize inference with quantization, pruning, distillation, or ONNX',
    'Compare Ollama, vLLM, TGI, LiteLLM, and optimized runtimes',
    'Plan capacity, batching, and GPU utilization for production traffic',
  ],
  '12.6 Containerization & Orchestration': [
    'Package AI services with Docker and multi-stage builds',
    'Run local dependencies together with Docker Compose',
    'Deploy services and configuration with Kubernetes and Helm',
    'Scale workloads and schedule GPU resources safely',
  ],
  '12.7 Cloud Deployment': [
    'Compare AWS compute, managed ML, object storage, and monitoring',
    'Use GCP Vertex AI, Cloud Run, GKE, or BigQuery as appropriate',
    'Use Azure ML, Azure OpenAI, or AKS for corresponding workloads',
    'Choose managed services based on operational needs and cost',
  ],
  '12.8 Monitoring & Logging': [
    'Track token usage, latency percentiles, errors, and per-feature cost',
    'Monitor response quality, hallucinations, and behavior drift',
    'Instrument traces and LLM calls with observability platforms',
    'Connect metrics to dashboards, alerts, and error reporting',
  ],
  '12.9 CI/CD for AI': [
    'Automate application and model tests in a CI pipeline',
    'Validate candidate models before deployment',
    'Run prompt regression and automated evaluation suites',
    'Use feature flags and progressive deployment strategies',
  ],
  '12.10 LLM Security & Safety': [
    'Separate instructions and untrusted input; validate model outputs',
    'Test direct and indirect prompt injection and scan uploaded files',
    'Moderate inputs and outputs with policy-specific checks',
    'Mask sensitive data and account for residency and audit requirements',
  ],
  '13.1 AI System Design Framework': [
    'Clarify functional requirements and service-level constraints',
    'Identify which product tasks genuinely need AI',
    'Draw data flows and select models per task',
    'Estimate scale, cost, failure handling, and monitoring needs',
  ],
  '13.2 Classic AI System Designs': [
    'Design a chatbot with session memory, context building, and fallbacks',
    'Design document ingestion, retrieval, reranking, and answer generation',
    'Design recommendation flows with embeddings, ranking, and feedback',
    'Plan queueing, caching, streaming, and human escalation at scale',
  ],
  '13.3 Inference Placement Strategy': [
    'Compare backend, browser/client, edge, and asynchronous inference',
    'Balance privacy, latency, model size, reliability, and operating complexity',
    'Choose placement based on task urgency and deployment constraints',
  ],
  '13.4 Caching Strategies': [
    'Cache exact prompt matches with stable fingerprints',
    'Use embedding similarity for semantic cache lookups',
    'Cache reusable prompt templates separately from user-specific output',
    'Set cache thresholds, expiry, and invalidation rules',
  ],
  '13.5 Async AI Architecture': [
    'Move long-running or costly work to background processing',
    'Return task identifiers and expose polling or webhook completion',
    'Persist job state and communicate retries and failures',
  ],
  '13.6 Cost-Aware Architecture': [
    'Choose models by feature complexity and required quality',
    'Reduce prompt and response tokens with explicit limits',
    'Use caching, model tiers, and asynchronous batching to control spend',
    'Track cost by user and product feature',
  ],
  '14.1 Core SQL': [
    'Filter and sort records with SELECT, WHERE, ORDER BY, and LIMIT',
    'Combine tables with inner, outer, and self joins',
    'Group records and aggregate with COUNT, SUM, AVG, MIN, and MAX',
    'Handle nulls and common conditional predicates',
  ],
  '14.2 Advanced SQL': [
    'Compose queries with CTEs and nested subqueries',
    'Use ranking, lag/lead, and aggregate window functions',
    'Distinguish PARTITION BY from GROUP BY',
    'Apply CASE and COALESCE for conditional and null handling',
  ],
  '14.3 AI-Specific SQL Patterns': [
    'Prepare training and feature data with derived and rolling values',
    'Query JSON columns and sample records for analysis',
    'Run pgvector similarity searches with distance operators',
    'Create and compare HNSW and IVFFlat vector indexes',
  ],
  '14.4 Database Design for AI Applications': [
    'Model users, conversations, and message history',
    'Store prompt versions, model outputs, and evaluation results',
    'Record token use and user preferences or memory',
    'Index and partition data for AI workload access patterns',
  ],
  '14.5 NoSQL for AI': [
    'Use Redis for session state, caching, limits, and pub/sub',
    'Store flexible model outputs in document databases when suitable',
    'Evaluate serverless key-value stores for high-throughput workloads',
    'Choose SQL or NoSQL based on query, consistency, and data needs',
  ],
  '15.1 Model Quantization': [
    'Compare FP32, FP16, BF16, INT8, and INT4 precision',
    'Distinguish post-training quantization from quantization-aware training',
    'Compare GPTQ, AWQ, and GGUF approaches and formats',
    'Quantize and load models with bitsandbytes-style tooling',
  ],
  '15.2 Inference Optimization': [
    'Reuse key/value states with the KV cache',
    'Batch concurrent requests with continuous batching',
    'Use speculative decoding and efficient attention where supported',
    'Scale inference with tensor and pipeline parallelism',
  ],
  '15.3 Small Language Models (SLMs)': [
    'Compare compact model families such as Phi, Gemma, Mistral, and Qwen',
    'Select SLMs for narrow tasks where cost and latency matter',
    'Evaluate task-specific fine-tuning against a larger general model',
    'Explore on-device deployment constraints and capabilities',
  ],
  '15.4 Knowledge Distillation': [
    'Train a student from teacher outputs and soft targets',
    'Distill intermediate representations when useful',
    'Compare distilled model examples such as DistilBERT and TinyLlama',
    'Measure the quality and serving-cost trade-off of smaller models',
  ],
  '15.5 Model Serving Efficiency': [
    'Compare vLLM, TGI, Ollama, llama.cpp, and ONNX Runtime',
    'Understand paged attention and continuous batching for throughput',
    'Select CPU, GPU, or optimized vendor runtimes for a workload',
    'Benchmark latency, memory, concurrency, and tokens per second',
  ],
  '16.1 RL Fundamentals': [
    'Represent an environment with states, actions, rewards, and transitions',
    'Define policies, value functions, and Q-functions',
    'Balance exploration and exploitation with common strategies',
    'Understand discounting and Markov decision processes',
  ],
  '16.2 Value-Based Methods': [
    'Implement Q-learning and estimate action values',
    'Train a DQN with replay and target-network concepts',
    'Compare Double/Dueling DQN and prioritized replay improvements',
  ],
  '16.3 Policy-Based Methods': [
    'Optimize policies with REINFORCE-style gradients',
    'Combine actor and critic estimates',
    'Understand PPO clipping and its role in preference optimization',
    'Recognize group-relative policy optimization approaches',
  ],
  '16.4 RL for LLMs (RLHF & Beyond)': [
    'Trace the supervised fine-tuning, reward-model, and PPO pipeline',
    'Train reward models from preference comparisons',
    'Compare DPO and AI-generated feedback approaches',
    'Understand KL constraints and process- versus outcome-based rewards',
  ],
  '16.5 Multi-Agent RL': [
    'Compare cooperative and competitive agents',
    'Apply game-theory concepts and self-play',
    'Study communication and coordination among agents',
  ],
  '17.1 AI Safety Fundamentals': [
    'Identify immediate, systemic, and longer-term AI harms',
    'Relate alignment to intended behavior and objectives',
    'Recognize hallucination, bias, and dual-use risks',
    'Assess risks in the context of a deployed product',
  ],
  '17.2 Prompt Injection & Security': [
    'Distinguish direct user injection from malicious retrieved content',
    'Use instruction separation, validation, and output filtering as defenses',
    'Test jailbreak patterns with structured red-team exercises',
    'Limit tool permissions and monitor suspicious inputs',
  ],
  '17.3 Bias & Fairness': [
    'Trace bias to data, labeling, measurement, or model choices',
    'Compare demographic parity and equalized-odds measures',
    'Audit systems with fairness tooling',
    'Evaluate mitigation options such as resampling and reweighting',
  ],
  '17.4 Privacy & Data Governance': [
    'Find and protect personal information in training and inference data',
    'Apply data minimization and privacy compliance requirements',
    'Plan deletion workflows and differential privacy safeguards',
    'Compare centralized training with federated approaches',
  ],
  '17.5 AI Transparency & Explainability': [
    'Document capabilities and limitations with model/system cards',
    'Use SHAP and LIME while understanding their limits',
    'Visualize model signals carefully and avoid overstating explanations',
    'Communicate system behavior to users and reviewers',
  ],
  '17.6 Responsible AI in Production': [
    'Add moderation, safety classifiers, and human review for high-risk cases',
    'Maintain audit trails and an incident-response process',
    'Apply governance frameworks such as NIST AI RMF and relevant regulation',
    'Reassess safety as models, prompts, and usage change',
  ],
  'API Gateway': ['Authenticate users, apply rate limits, and route requests'],
  'Multi-LLM Router': ['Select providers by task, quality, availability, and cost'],
  'RAG Engine': ['Ingest multiple document types and isolate tenant retrieval'],
  'Agent Orchestrator': ['Run tool-using and multi-agent workflows with controlled state'],
  'MCP Integration': ['Connect platform tools through Model Context Protocol'],
  'Observability Stack': ['Trace requests and monitor service, model, and cost metrics'],
  'Admin Dashboard': ['Review usage analytics, spend, and model performance'],
  'CI/CD Pipeline': ['Automate tests, validation, and deployment'],
  'Multi-tenant user management': ['Isolate organizations, users, and their data'],
  'Per-user API key management': ['Store, protect, rotate, and scope user credentials'],
  'Streaming responses': ['Stream model output to clients while handling partial results'],
  'Conversation memory': ['Persist conversation state and retrieve relevant history'],
  'Prompt version management': ['Version prompts and retain change history'],
  'A/B testing for prompts and models': ['Compare variants with defined outcome metrics'],
  'Cost tracking dashboard': ['Attribute token and provider costs to users and features'],
  'Usage limits and billing': ['Enforce quotas and expose usage for billing'],
};